// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaExample.Data;

#nullable disable

namespace PizzaExample.Data.Migrations
{
    [DbContext(typeof(PizzaContext))]
    [Migration("20240214161459_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PizzaExample.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Calorias")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calorias = 34,
                            Name = "Peperoni",
                            Origen = "Animal",
                            PizzaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Calorias = 56,
                            Name = "Queso",
                            Origen = "Animal",
                            PizzaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Calorias = 27,
                            Name = "Jamon",
                            Origen = "Animal",
                            PizzaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Calorias = 4,
                            Name = "Oregano",
                            Origen = "Vegetal",
                            PizzaId = 1
                        });
                });

            modelBuilder.Entity("PizzaExample.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsGlutenFree = false,
                            Name = "Peperoni"
                        },
                        new
                        {
                            Id = 2,
                            IsGlutenFree = false,
                            Name = "Jamon y queso"
                        });
                });

            modelBuilder.Entity("PizzaExample.Models.Ingrediente", b =>
                {
                    b.HasOne("PizzaExample.Models.Pizza", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaExample.Models.Pizza", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
